# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('goods', '0001_initial'),
        ('data', '0001_initial'),
        ('stock_transfer', '0001_initial'),
        ('system', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('type', models.CharField(choices=[('purchase', '采购'), ('sales_return', '销售退货'), ('stock_transfer', '调拨')], max_length=32, verbose_name='入库类型')),
                ('total_quantity', models.FloatField(verbose_name='入库总数')),
                ('remain_quantity', models.FloatField(default=0, verbose_name='入库剩余数量')),
                ('is_completed', models.BooleanField(default=False, verbose_name='入库完成状态')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_in_orders', to='system.user', verbose_name='创建人')),
                ('purchase_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_order', to='purchase.purchaseorder', verbose_name='采购单据')),
                ('sales_return_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_order', to='sales.salesreturnorder', verbose_name='销售退货单据')),
                ('stock_transfer_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_order', to='stock_transfer.stocktransferorder', verbose_name='调拨单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_orders', to='system.team')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_orders', to='data.warehouse', verbose_name='仓库')),
            ],
            options={
                'unique_together': {('number', 'team')},
            },
        ),
        migrations.CreateModel(
            name='StockInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('total_quantity', models.FloatField(null=True, verbose_name='入库总数')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_in_records', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_records', to='system.user', verbose_name='经手人')),
                ('stock_in_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_records', to='stock_in.stockinorder', verbose_name='入库通知单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_records', to='system.team')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_records', to='data.warehouse', verbose_name='仓库')),
            ],
        ),
        migrations.CreateModel(
            name='StockInGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in_quantity', models.FloatField(verbose_name='入库总数')),
                ('remain_quantity', models.FloatField(default=0, verbose_name='入库剩余数量')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完成状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_goods_set', to='goods.goods', verbose_name='产品')),
                ('stock_in_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_goods_set', to='stock_in.stockinorder', verbose_name='入库通知单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_goods_set', to='system.team')),
            ],
            options={
                'unique_together': {('stock_in_order', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='StockInRecordGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in_quantity', models.FloatField(verbose_name='入库数量')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_record_goods_set', to='goods.batch', verbose_name='批次')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_record_goods_set', to='goods.goods', verbose_name='产品')),
                ('stock_in_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_record_goods_set', to='stock_in.stockingoods', verbose_name='入库产品')),
                ('stock_in_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_record_goods_set', to='stock_in.stockinrecord', verbose_name='入库记录')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_record_goods_set', to='system.team')),
            ],
            options={
                'unique_together': {('stock_in_record', 'goods')},
            },
        ),
    ]
