# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion
import extensions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('total_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, null=True, verbose_name='总金额')),
                ('discount_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='优惠金额')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_orders', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='system.user', verbose_name='经手人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='data.supplier', verbose_name='供应商')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='system.team')),
            ],
            options={
                'unique_together': {('number', 'team')},
            },
        ),
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('total_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, null=True, verbose_name='总金额')),
                ('discount_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='优惠金额')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_orders', to='data.client', verbose_name='客户')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_collection_orders', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_orders', to='system.user', verbose_name='经手人')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_orders', to='system.team')),
            ],
            options={
                'unique_together': {('number', 'team')},
            },
        ),
        migrations.CreateModel(
            name='AccountTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_out_time', models.DateTimeField(verbose_name='转出时间')),
                ('transfer_in_time', models.DateTimeField(verbose_name='转入时间')),
                ('transfer_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='转账金额')),
                ('service_charge_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='手续费金额')),
                ('service_charge_payer', models.CharField(choices=[('transfer_in', '转入方'), ('transfer_out', '转出方')], default='transfer_out', max_length=32, verbose_name='手续费支付方')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_account_transfer_records', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_transfer_records', to='system.user', verbose_name='经手人')),
                ('in_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_account_transfer_records', to='data.account', verbose_name='转入账户')),
                ('out_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_account_transfer_records', to='data.account', verbose_name='转出账户')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transfer_records', to='system.team')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='付款金额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_accounts', to='data.account', verbose_name='结算账户')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='finance.paymentorder', verbose_name='付款单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='system.team')),
            ],
            options={
                'unique_together': {('payment_order', 'account')},
            },
        ),
        migrations.CreateModel(
            name='CollectionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='收款金额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_accounts', to='data.account', verbose_name='结算账户')),
                ('collection_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_accounts', to='finance.collectionorder', verbose_name='收款单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_accounts', to='system.team')),
            ],
            options={
                'unique_together': {('collection_order', 'account')},
            },
        ),
        migrations.CreateModel(
            name='ChargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('type', models.CharField(choices=[('income', '收入'), ('expenditure', '支出')], max_length=32, verbose_name='收支类型')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('charge_item_name', models.CharField(max_length=64, verbose_name='收支项目名称')),
                ('total_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='应收/付金额')),
                ('charge_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='实收/付金额')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_orders', to='data.account', verbose_name='结算账户')),
                ('charge_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_orders', to='data.chargeitem', verbose_name='收支项目')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_orders', to='data.client', verbose_name='客户')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_charge_orders', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_orders', to='system.user', verbose_name='经手人')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_orders', to='data.supplier', verbose_name='供应商')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_orders', to='system.team')),
            ],
            options={
                'unique_together': {('number', 'team')},
            },
        ),
    ]
