# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('serial_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='序列号')),
                ('account_ownership', models.CharField(blank=True, max_length=256, null=True, verbose_name='账号归属')),
            ],
        ),
    ]
