# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('goods', '0001_initial'),
        ('finance', '0001_initial'),
        ('stock_in', '0001_initial'),
        ('data', '0001_initial'),
        ('stock_out', '0001_initial'),
        ('stock_transfer', '0001_initial'),
        ('stock_check', '0001_initial'),
        ('system', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', '采购'), ('void_purchase', '作废采购'), ('purchase_return', '采购退货'), ('void_purchase_return', '作废采购退货'), ('sales', '销售'), ('void_sales', '作废销售'), ('sales_return', '销售退货'), ('void_sales_return', '作废销售退货'), ('stock_in', '入库'), ('void_stock_in', '作废入库'), ('stock_out', '出库'), ('void_stock_out', '作废出库'), ('stock_check', '盘点'), ('void_stock_check', '作废盘点'), ('stock_transfer_out', '调拨转出'), ('void_stock_transfer_out', '作废调拨转出'), ('stock_transfer_in', '调拨转入'), ('void_stock_transfer_in', '作废调拨转入')], max_length=32, verbose_name='流水类型')),
                ('quantity_before', models.FloatField(verbose_name='变化之前数量')),
                ('quantity_change', models.FloatField(verbose_name='变化数量')),
                ('quantity_after', models.FloatField(verbose_name='变化之后数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_flows', to='system.user', verbose_name='创建人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_flows', to='goods.goods', verbose_name='产品')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_flows', to='purchase.purchaseorder', verbose_name='采购单据')),
                ('purchase_return_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_flows', to='purchase.purchasereturnorder', verbose_name='采购退货单据')),
                ('sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_flows', to='sales.salesorder', verbose_name='销售单据')),
                ('sales_return_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_flows', to='sales.salesreturnorder', verbose_name='销售退货单据')),
                ('stock_check_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_flows', to='stock_check.stockcheckorder', verbose_name='盘点单据')),
                ('stock_in_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_flows', to='stock_in.stockinorder', verbose_name='入库通知单据')),
                ('stock_out_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_flows', to='stock_out.stockoutorder', verbose_name='出库通知单据')),
                ('stock_transfer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_flows', to='stock_transfer.stocktransferorder', verbose_name='调拨单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_flows', to='system.team')),
                ('void_purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_inventory_flows', to='purchase.purchaseorder', verbose_name='作废采购单据')),
                ('void_purchase_return_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_inventory_flows', to='purchase.purchasereturnorder', verbose_name='作废采购退货单据')),
                ('void_sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_inventory_flows', to='sales.salesorder', verbose_name='作废销售单据')),
                ('void_sales_return_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_inventory_flows', to='sales.salesreturnorder', verbose_name='作废销售退货单据')),
                ('void_stock_check_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_inventory_flows', to='stock_check.stockcheckorder', verbose_name='作废盘点单据')),
                ('void_stock_in_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_inventory_flows', to='stock_in.stockinorder', verbose_name='作废入库通知单据')),
                ('void_stock_out_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_inventory_flows', to='stock_out.stockoutorder', verbose_name='作废出库通知单据')),
                ('void_stock_transfer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_inventory_flows', to='stock_transfer.stocktransferorder', verbose_name='作废调拨单据')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_flows', to='data.warehouse', verbose_name='仓库')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', '采购'), ('void_purchase', '作废采购'), ('purchase_return', '采购退货'), ('void_purchase_return', '作废采购退货'), ('sales', '销售'), ('void_sales', '作废销售'), ('sales_return', '销售退货'), ('void_sales_return', '作废销售退货'), ('payment', '付款'), ('void_payment', '作废付款'), ('collection', '收款'), ('void_collection', '作废收款'), ('charge', '收支'), ('void_charge', '作废收支'), ('account_transfer_out', '转账转出'), ('void_account_transfer_out', '作废转账转出'), ('account_transfer_in', '转账转入'), ('void_account_transfer_in', '作废转账转入')], max_length=32, verbose_name='流水类型')),
                ('amount_before', models.FloatField(verbose_name='变化之前余额')),
                ('amount_change', models.FloatField(verbose_name='变化余额')),
                ('amount_after', models.FloatField(verbose_name='变化之后余额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_flows', to='data.account', verbose_name='结算账户')),
                ('account_transfer_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_flows', to='finance.accounttransferrecord', verbose_name='转账记录')),
                ('charge_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_flows', to='finance.chargeorder', verbose_name='收支单据')),
                ('collection_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_flows', to='finance.collectionorder', verbose_name='收款单据')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_flows', to='system.user', verbose_name='创建人')),
                ('payment_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_flows', to='finance.paymentorder', verbose_name='付款单据')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_flows', to='purchase.purchaseorder', verbose_name='采购单据')),
                ('purchase_return_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_flows', to='purchase.purchasereturnorder', verbose_name='采购退货单据')),
                ('sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_flows', to='sales.salesorder', verbose_name='销售单据')),
                ('sales_return_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_flows', to='sales.salesreturnorder', verbose_name='销售退货单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_flows', to='system.team')),
                ('void_account_transfer_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_finance_flows', to='finance.accounttransferrecord', verbose_name='作废转账记录')),
                ('void_charge_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_finance_flows', to='finance.chargeorder', verbose_name='作废收支单据')),
                ('void_collection_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_finance_flows', to='finance.collectionorder', verbose_name='作废收款单据')),
                ('void_payment_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_finance_flows', to='finance.paymentorder', verbose_name='作废付款单据')),
                ('void_purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_finance_flows', to='purchase.purchaseorder', verbose_name='作废采购单据')),
                ('void_purchase_return_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_finance_flows', to='purchase.purchasereturnorder', verbose_name='作废采购退货单据')),
                ('void_sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_finance_flows', to='sales.salesorder', verbose_name='作废销售单据')),
                ('void_sales_return_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='void_finance_flows', to='sales.salesreturnorder', verbose_name='作废销售退货单据')),
            ],
        ),
    ]
