# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('goods', '0001_initial'),
        ('data', '0001_initial'),
        ('stock_transfer', '0001_initial'),
        ('system', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('type', models.CharField(choices=[('sales', '销售'), ('purchase', '采购退货'), ('stock_transfer', '调拨')], max_length=32, verbose_name='出库类型')),
                ('total_quantity', models.FloatField(verbose_name='出库总数')),
                ('remain_quantity', models.FloatField(default=0, verbose_name='出库剩余数量')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完成状态')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_out_orders', to='system.user', verbose_name='创建人')),
                ('purchase_return_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_order', to='purchase.purchasereturnorder', verbose_name='采购退货单据')),
                ('sales_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_order', to='sales.salesorder', verbose_name='销售单据')),
                ('stock_transfer_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_order', to='stock_transfer.stocktransferorder', verbose_name='调拨单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_orders', to='system.team')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_orders', to='data.warehouse', verbose_name='仓库')),
            ],
            options={
                'unique_together': {('number', 'team')},
            },
        ),
        migrations.CreateModel(
            name='StockOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('total_quantity', models.FloatField(null=True, verbose_name='出库总数')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_out_records', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_records', to='system.user', verbose_name='经手人')),
                ('stock_out_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_records', to='stock_out.stockoutorder', verbose_name='出库通知单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_records', to='system.team')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_records', to='data.warehouse', verbose_name='仓库')),
            ],
        ),
        migrations.CreateModel(
            name='StockOutGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_out_quantity', models.FloatField(verbose_name='出库总数')),
                ('remain_quantity', models.FloatField(default=0, verbose_name='出库剩余数量')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完成状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_goods_set', to='goods.goods', verbose_name='产品')),
                ('stock_out_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_goods_set', to='stock_out.stockoutorder', verbose_name='出库通知单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_goods_set', to='system.team')),
            ],
            options={
                'unique_together': {('stock_out_order', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='StockOutRecordGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_out_quantity', models.FloatField(verbose_name='出库数量')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_record_goods_set', to='goods.batch', verbose_name='批次')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_record_goods_set', to='goods.goods', verbose_name='产品')),
                ('stock_out_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_record_goods_set', to='stock_out.stockoutgoods', verbose_name='出库产品')),
                ('stock_out_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_record_goods_set', to='stock_out.stockoutrecord', verbose_name='出库记录')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_record_goods_set', to='system.team')),
            ],
            options={
                'unique_together': {('stock_out_record', 'goods')},
            },
        ),
    ]
