# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('goods', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('total_quantity', models.FloatField(null=True, verbose_name='调拨总数量')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('enable_auto_stock_out', models.BooleanField(default=False, verbose_name='启用自动出库')),
                ('enable_auto_stock_in', models.BooleanField(default=False, verbose_name='启用自动入库')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_transfer_orders', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_orders', to='system.user', verbose_name='经手人')),
                ('in_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_stock_transfer_orders', to='data.warehouse', verbose_name='入库仓库')),
                ('out_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_stock_transfer_orders', to='data.warehouse', verbose_name='出库仓库')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_orders', to='system.team')),
            ],
            options={
                'unique_together': {('number', 'team')},
            },
        ),
        migrations.CreateModel(
            name='StockTransferGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_transfer_quantity', models.FloatField(verbose_name='调拨数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_goods_set', to='goods.goods', verbose_name='产品')),
                ('stock_transfer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_goods_set', to='stock_transfer.stocktransferorder', verbose_name='采购单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_goods_set', to='system.team')),
            ],
            options={
                'unique_together': {('stock_transfer_order', 'goods')},
            },
        ),
    ]
