# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('barcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='条码')),
                ('spec', models.CharField(blank=True, max_length=64, null=True, verbose_name='规格')),
                ('enable_batch_control', models.BooleanField(default=False, verbose_name='启用批次控制')),
                ('shelf_life_days', models.IntegerField(null=True, verbose_name='保质期天数')),
                ('shelf_life_warning_days', models.IntegerField(default=0, verbose_name='保质期预警天数')),
                ('enable_inventory_warning', models.BooleanField(default=False, verbose_name='启用库存警告')),
                ('inventory_upper', models.FloatField(null=True, verbose_name='库存上限')),
                ('inventory_lower', models.FloatField(null=True, verbose_name='库存下限')),
                ('purchase_price', models.FloatField(default=0, verbose_name='采购价')),
                ('retail_price', models.FloatField(default=0, verbose_name='零售价')),
                ('level_price1', models.FloatField(default=0, verbose_name='等级价一')),
                ('level_price2', models.FloatField(default=0, verbose_name='等级价二')),
                ('level_price3', models.FloatField(default=0, verbose_name='等级价三')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.FloatField(default=0, verbose_name='初始库存')),
                ('total_quantity', models.FloatField(default=0, verbose_name='库存总数')),
                ('has_stock', models.BooleanField(default=False, verbose_name='库存状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='goods.goods', verbose_name='产品')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='system.team')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='data.warehouse', verbose_name='仓库')),
            ],
            options={
                'unique_together': {('warehouse', 'goods', 'team')},
            },
        ),
        migrations.CreateModel(
            name='GoodsUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_units', to='system.team')),
            ],
            options={
                'unique_together': {('name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='文件')),
                ('name', models.CharField(max_length=256, verbose_name='文件名称')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_images', to='goods.goods', verbose_name='产品')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_images', to='system.team')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_categories', to='system.team')),
            ],
            options={
                'unique_together': {('name', 'team')},
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_set', to='goods.goodscategory', verbose_name='产品分类'),
        ),
        migrations.AddField(
            model_name='goods',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_set', to='system.team'),
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_set', to='goods.goodsunit', verbose_name='产品单位'),
        ),
        migrations.AlterUniqueTogether(
            name='goods',
            unique_together={('number', 'team')},
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('initial_quantity', models.FloatField(default=0, verbose_name='初始库存')),
                ('total_quantity', models.FloatField(verbose_name='批次数量')),
                ('remain_quantity', models.FloatField(verbose_name='批次剩余数量')),
                ('production_date', models.DateField(null=True, verbose_name='生产日期')),
                ('shelf_life_days', models.IntegerField(null=True, verbose_name='保质期天数')),
                ('warning_date', models.DateField(null=True, verbose_name='预警日期')),
                ('expiration_date', models.DateField(null=True, verbose_name='过期日期')),
                ('has_stock', models.BooleanField(default=True, verbose_name='库存状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchs', to='goods.goods', verbose_name='产品')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchs', to='goods.inventory', verbose_name='库存')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchs', to='system.team')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchs', to='data.warehouse', verbose_name='仓库')),
            ],
            options={
                'unique_together': {('number', 'warehouse', 'goods', 'team')},
            },
        ),
    ]
