# Generated by Django 3.2 on 2025-06-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='enable_inventory_warning',
            field=models.BooleanField(default=True, verbose_name='启用库存警告'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='inventory_lower',
            field=models.FloatField(default=1, verbose_name='库存下限'),
        ),
    ]
