# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion
import extensions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='system.user', verbose_name='管理员')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='system.team')),
            ],
            options={
                'unique_together': {('number', 'team'), ('name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='地址')),
                ('bank_account', models.CharField(blank=True, max_length=64, null=True, verbose_name='银行账户')),
                ('bank_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='开户行')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('initial_arrears_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='初期欠款金额')),
                ('arrears_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='欠款金额')),
                ('has_arrears', models.BooleanField(default=False, verbose_name='欠款状态')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='system.team')),
            ],
            options={
                'unique_together': {('number', 'team'), ('name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('level', models.CharField(choices=[('0', '普通客户'), ('1', '一级客户'), ('2', '二级客户'), ('3', '三级客户')], default='0', max_length=32, verbose_name='等级')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('initial_arrears_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='初期欠款金额')),
                ('arrears_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='欠款金额')),
                ('has_arrears', models.BooleanField(default=False, verbose_name='欠款状态')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='system.team')),
            ],
            options={
                'unique_together': {('number', 'team'), ('name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('type', models.CharField(choices=[('income', '收入'), ('expenditure', '支出')], max_length=32, verbose_name='收支类型')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_items', to='system.team')),
            ],
            options={
                'unique_together': {('name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('type', models.CharField(choices=[('cash', '现金'), ('alipay', '支付宝'), ('wechat', '微信'), ('bank_account', '银行账户'), ('other', '其他')], default='cash', max_length=32, verbose_name='账户类型')),
                ('holder', models.CharField(blank=True, max_length=64, null=True, verbose_name='开户人')),
                ('card_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='开户账号')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('initial_balance_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='初期余额')),
                ('balance_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='余额')),
                ('has_balance', models.BooleanField(default=False, verbose_name='余额状态')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='system.team')),
            ],
            options={
                'unique_together': {('number', 'team'), ('name', 'team')},
            },
        ),
    ]
