# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion
import extensions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('goods', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('total_quantity', models.FloatField(null=True, verbose_name='销售总数量')),
                ('discount', models.FloatField(default=1, verbose_name='整单折扣')),
                ('other_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='其他费用')),
                ('total_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, null=True, verbose_name='销售总金额')),
                ('collection_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, null=True, verbose_name='收款金额')),
                ('arrears_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, null=True, verbose_name='欠款金额')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('enable_auto_stock_out', models.BooleanField(default=False, verbose_name='启用自动出库')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='data.client', verbose_name='客户')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_orders', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='system.user', verbose_name='经手人')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='system.team')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='data.warehouse', verbose_name='仓库')),
            ],
            options={
                'unique_together': {('number', 'team')},
            },
        ),
        migrations.CreateModel(
            name='SalesReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('total_quantity', models.FloatField(null=True, verbose_name='退货总数量')),
                ('other_amount', extensions.models.AmountField(decimal_places=2, default=0, max_digits=16, verbose_name='其他费用')),
                ('total_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, null=True, verbose_name='退货总金额')),
                ('payment_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, null=True, verbose_name='付款金额')),
                ('arrears_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, null=True, verbose_name='欠款金额')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('enable_auto_stock_in', models.BooleanField(default=False, verbose_name='启用自动入库')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_orders', to='data.client', verbose_name='客户')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_return_orders', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_orders', to='system.user', verbose_name='经手人')),
                ('sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_orders', to='sales.salesorder', verbose_name='销售单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_orders', to='system.team')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_orders', to='data.warehouse', verbose_name='仓库')),
            ],
            options={
                'unique_together': {('number', 'team')},
            },
        ),
        migrations.CreateModel(
            name='SalesGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_quantity', models.FloatField(verbose_name='销售数量')),
                ('sales_price', models.FloatField(verbose_name='销售单价')),
                ('total_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='总金额')),
                ('return_quantity', models.FloatField(default=0, verbose_name='退货数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_goods_set', to='goods.goods', verbose_name='产品')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_goods_set', to='sales.salesorder', verbose_name='销售单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_goods_set', to='system.team')),
            ],
            options={
                'unique_together': {('sales_order', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='SalesReturnGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.FloatField(verbose_name='退货数量')),
                ('return_price', models.FloatField(verbose_name='退货单价')),
                ('total_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='总金额')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_goods_set', to='goods.goods', verbose_name='产品')),
                ('sales_goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_goods_set', to='sales.salesgoods', verbose_name='销售产品')),
                ('sales_return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_goods_set', to='sales.salesreturnorder', verbose_name='销售退货单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_goods_set', to='system.team')),
            ],
            options={
                'unique_together': {('sales_return_order', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='SalesReturnAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='付款金额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_accounts', to='data.account', verbose_name='结算账户')),
                ('sales_return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_accounts', to='sales.salesreturnorder', verbose_name='销售退货单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_accounts', to='system.team')),
            ],
            options={
                'unique_together': {('sales_return_order', 'account')},
            },
        ),
        migrations.CreateModel(
            name='SalesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='收款金额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_accounts', to='data.account', verbose_name='结算账户')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_accounts', to='sales.salesorder', verbose_name='销售单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_accounts', to='system.team')),
            ],
            options={
                'unique_together': {('sales_order', 'account')},
            },
        ),
    ]
