# Generated by Django 3.2 on 2025-06-16 8:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_count', models.IntegerField(default=0, verbose_name='今日销售笔数')),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='今日销售额')),
                ('purchase_count', models.IntegerField(default=0, verbose_name='今日采购笔数')),
                ('stock_in_task_count', models.IntegerField(default=0, verbose_name='待入库数')),
                ('stock_out_task_count', models.IntegerField(default=0, verbose_name='待出库数')),
                ('inventory_warning_count', models.IntegerField(default=0, verbose_name='库存预警数')),
                ('expiration_warning_count', models.IntegerField(default=0, verbose_name='临期预警数')),
                ('arrears_receivable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收欠款')),
                ('arrears_payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应付欠款')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_statistics', to='system.team')),
            ],
            options={
                'verbose_name': '数据看板统计',
                'verbose_name_plural': '数据看板统计',
                'unique_together': {('team',)},
            },
        ),
    ]
