# Generated by Django 3.2 on 2025-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardstatistics',
            name='hot_goods_data',
            field=models.JSONField(default=dict, verbose_name='热销商品数据'),
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='sales_trend_data',
            field=models.JSONField(default=dict, verbose_name='销售走势数据'),
        ),
    ]
