# Generated by Django 3.2 on 2025-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion
import extensions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('goods', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCheckOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('surplus', '盘盈'), ('loss', '盘亏'), ('unchanged', '无变化')], max_length=32, null=True, verbose_name='盘点状态')),
                ('total_book_quantity', models.FloatField(null=True, verbose_name='账面总数量')),
                ('total_actual_quantity', models.FloatField(null=True, verbose_name='实际总数量')),
                ('total_surplus_quantity', models.FloatField(null=True, verbose_name='盘盈总数量')),
                ('total_surplus_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, null=True, verbose_name='盘盈总金额')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_check_orders', to='system.user', verbose_name='创建人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_check_orders', to='system.user', verbose_name='经手人')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_check_orders', to='system.team')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_check_orders', to='data.warehouse', verbose_name='仓库')),
            ],
            options={
                'unique_together': {('number', 'team')},
            },
        ),
        migrations.CreateModel(
            name='StockCheckGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_quantity', models.FloatField(verbose_name='账面数量')),
                ('actual_quantity', models.FloatField(verbose_name='实际数量')),
                ('surplus_quantity', models.FloatField(verbose_name='盘盈数量')),
                ('purchase_price', models.FloatField(verbose_name='采购单价')),
                ('surplus_amount', extensions.models.AmountField(decimal_places=2, max_digits=16, verbose_name='盘盈金额')),
                ('status', models.CharField(choices=[('surplus', '盘盈'), ('loss', '盘亏'), ('unchanged', '无变化')], max_length=32, verbose_name='盘点状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_check_goods_set', to='goods.goods', verbose_name='产品')),
                ('stock_check_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_check_goods_set', to='stock_check.stockcheckorder', verbose_name='盘点单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_check_goods_set', to='system.team')),
            ],
            options={
                'unique_together': {('stock_check_order', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='StockCheckBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=32, verbose_name='批次编号')),
                ('production_date', models.DateField(null=True, verbose_name='生产日期')),
                ('book_quantity', models.FloatField(verbose_name='账面数量')),
                ('actual_quantity', models.FloatField(verbose_name='实际数量')),
                ('surplus_quantity', models.FloatField(verbose_name='盘盈数量')),
                ('status', models.CharField(choices=[('surplus', '盘盈'), ('loss', '盘亏'), ('unchanged', '无变化')], max_length=32, verbose_name='盘点状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_check_batchs', to='goods.goods', verbose_name='产品')),
                ('stock_check_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_check_batchs', to='stock_check.stockcheckgoods', verbose_name='盘点产品')),
                ('stock_check_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_check_batchs', to='stock_check.stockcheckorder', verbose_name='盘点单据')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_check_batchs', to='system.team')),
            ],
            options={
                'unique_together': {('stock_check_goods', 'batch_number')},
            },
        ),
    ]
